// Mock order list matching DINE QR schema and active business flows.
// Note: PENDING tickets (such as 1040) start with waiter: null. Cancelled orders are removed.
export const INITIAL_ORDERS = [
  {
    _id: "1042",
    table: {
      id: "table_12",
      number: "12",
      floor: "Main Floor",
      status: "Occupied",
    },
    customer: {
      name: "Table Guest",
    },
    items: [
      {
        productId: "p1",
        name: "Chicken Biriyani",
        quantity: 1,
        price: 32.0,
        addons: ["Extra Raita", "Mild Spice"],
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=150&q=80",
      },
      {
        productId: "p2",
        name: "Paneer Tikka",
        quantity: 1,
        price: 24.0,
        addons: [],
        image: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=150&q=80",
      },
      {
        productId: "p3",
        name: "Signature Mojito",
        quantity: 2,
        price: 28.5,
        addons: [],
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=150&q=80",
      },
    ],
    subtotal: 84.5,
    tax: 6.76,
    serviceCharge: 8.45,
    total: 99.71,
    status: "PREPARING",
    waiter: {
      id: "w1",
      name: "Arun K.",
      avatar: "AK",
      ordersToday: 14,
    },
    timeline: [
      {
        status: "PLACED",
        timestamp: "15:21",
        performedBy: "Customer",
        note: "Table 12 via Digital QR",
      },
      {
        status: "CONFIRMED",
        timestamp: "15:23",
        performedBy: "Arun K.",
        note: "Order confirmed by staff",
      },
      {
        status: "PREPARING",
        timestamp: "15:24",
        performedBy: "Kitchen",
        note: "Kitchen started preparation",
      },
    ],
    createdAt: "2026-08-20T15:21:00.000Z",
    updatedAt: "2026-08-20T15:24:00.000Z",
  },
  {
    _id: "1041",
    table: {
      id: "table_04",
      number: "04",
      floor: "Main Floor",
      status: "Occupied",
    },
    customer: {
      name: "Sarah Jenkins",
    },
    items: [
      {
        productId: "p4",
        name: "Truffle Pasta",
        quantity: 1,
        price: 36.0,
        addons: ["Gluten Free"],
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=150&q=80",
      },
      {
        productId: "p5",
        name: "Garlic Bread",
        quantity: 2,
        price: 8.0,
        addons: ["Extra Cheese"],
        image: "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=150&q=80",
      },
    ],
    subtotal: 52.0,
    tax: 4.16,
    serviceCharge: 5.2,
    total: 61.36,
    status: "SERVED",
    waiter: {
      id: "w2",
      name: "Sarah M.",
      avatar: "SM",
      ordersToday: 9,
    },
    timeline: [
      {
        status: "PLACED",
        timestamp: "15:01",
        performedBy: "Customer",
      },
      {
        status: "CONFIRMED",
        timestamp: "15:02",
        performedBy: "Sarah M.",
      },
      {
        status: "PREPARING",
        timestamp: "15:05",
        performedBy: "Kitchen",
      },
      {
        status: "READY",
        timestamp: "15:18",
        performedBy: "Kitchen",
      },
      {
        status: "SERVED",
        timestamp: "15:23",
        performedBy: "Sarah M.",
      },
    ],
    createdAt: "2026-08-20T15:01:00.000Z",
    updatedAt: "2026-08-20T15:23:00.000Z",
  },
  {
    _id: "1040",
    table: {
      id: "table_18",
      number: "18",
      floor: "Terrace Section",
      status: "Occupied",
    },
    customer: {
      name: "Table Guest",
    },
    items: [
      {
        productId: "p6",
        name: "Wagyu Steak",
        quantity: 1,
        price: 195.0,
        addons: ["Medium Rare", "Truffle Butter"],
        image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=150&q=80",
      },
      {
        productId: "p7",
        name: "Red Wine (Glass)",
        quantity: 2,
        price: 25.0,
        addons: ["Pinot Noir"],
        image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=150&q=80",
      },
    ],
    subtotal: 245.0,
    tax: 19.6,
    serviceCharge: 24.5,
    total: 289.1,
    status: "PENDING",
    waiter: null, // Pending orders start unassigned
    timeline: [
      {
        status: "PLACED",
        timestamp: "15:43",
        performedBy: "Customer",
        note: "Sent to pending verification",
      },
    ],
    createdAt: "2026-08-20T15:43:00.000Z",
    updatedAt: "2026-08-20T15:43:00.000Z",
  },
  {
    _id: "1039",
    table: {
      id: "table_07",
      number: "07",
      floor: "Main Floor",
      status: "Bill Requested",
    },
    customer: {
      name: "John Doe",
    },
    items: [
      {
        productId: "p8",
        name: "Margherita Pizza",
        quantity: 2,
        price: 14.0,
        addons: ["Thin Crust"],
        image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=150&q=80",
      },
    ],
    subtotal: 28.0,
    tax: 2.24,
    serviceCharge: 2.8,
    total: 33.04,
    status: "BILL_REQUESTED",
    waiter: {
      id: "w1",
      name: "Arun K.",
      avatar: "AK",
      ordersToday: 14,
    },
    timeline: [
      {
        status: "PLACED",
        timestamp: "14:38",
        performedBy: "Customer",
      },
      {
        status: "CONFIRMED",
        timestamp: "14:40",
        performedBy: "Arun K.",
      },
      {
        status: "PREPARING",
        timestamp: "14:42",
        performedBy: "Kitchen",
      },
      {
        status: "READY",
        timestamp: "14:58",
        performedBy: "Kitchen",
      },
      {
        status: "SERVED",
        timestamp: "15:02",
        performedBy: "Arun K.",
      },
      {
        status: "BILL_REQUESTED",
        timestamp: "15:23",
        performedBy: "Customer",
        note: "Cash requested",
      },
    ],
    createdAt: "2026-08-20T14:38:00.000Z",
    updatedAt: "2026-08-20T15:23:00.000Z",
  },
  {
    _id: "1038",
    table: {
      id: "table_vip",
      number: "VIP",
      floor: "VIP Lounge",
      status: "Occupied",
    },
    customer: {
      name: "Senator Hastings",
    },
    items: [
      {
        productId: "p9",
        name: "Lobster Thermidor",
        quantity: 2,
        price: 120.0,
        addons: ["Extra Butter"],
        image: "https://images.unsplash.com/photo-1559737607-b37d45df137f?w=150&q=80",
      },
      {
        productId: "p10",
        name: "Champagne Bottle",
        quantity: 2,
        price: 70.0,
        addons: ["Dom Perignon"],
        image: "https://images.unsplash.com/photo-1594487017992-f285223e761c?w=150&q=80",
      },
    ],
    subtotal: 380.0,
    tax: 30.4,
    serviceCharge: 38.0,
    total: 448.4,
    status: "COMPLETED",
    waiter: {
      id: "mgr",
      name: "Manager",
      avatar: "MG",
      ordersToday: 25,
    },
    timeline: [
      {
        status: "PLACED",
        timestamp: "13:30",
        performedBy: "Manager",
      },
      {
        status: "CONFIRMED",
        timestamp: "13:31",
        performedBy: "Manager",
      },
      {
        status: "PREPARING",
        timestamp: "13:35",
        performedBy: "Kitchen",
      },
      {
        status: "READY",
        timestamp: "14:05",
        performedBy: "Kitchen",
      },
      {
        status: "SERVED",
        timestamp: "14:10",
        performedBy: "Manager",
      },
      {
        status: "COMPLETED",
        timestamp: "14:42",
        performedBy: "Manager",
        note: "Paid via Card terminal",
      },
    ],
    createdAt: "2026-08-20T13:30:00.000Z",
    updatedAt: "2026-08-20T14:42:00.000Z",
  },
  {
    _id: "1043",
    table: {
      id: "table_15",
      number: "15",
      floor: "Main Floor",
      status: "Occupied",
    },
    customer: {
      name: "Table Guest",
    },
    items: [
      {
        productId: "p1",
        name: "Chicken Biriyani",
        quantity: 3,
        price: 32.0,
        addons: ["Extra Raita"],
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=150&q=80",
      },
    ],
    subtotal: 96.0,
    tax: 7.68,
    serviceCharge: 9.6,
    total: 113.28,
    status: "CONFIRMED",
    waiter: {
      id: "w2",
      name: "Sarah M.",
      avatar: "SM",
      ordersToday: 9,
    },
    timeline: [
      {
        status: "PLACED",
        timestamp: "15:35",
        performedBy: "Customer",
      },
      {
        status: "CONFIRMED",
        timestamp: "15:38",
        performedBy: "Sarah M.",
      },
    ],
    createdAt: "2026-08-20T15:35:00.000Z",
    updatedAt: "2026-08-20T15:38:00.000Z",
  },
  {
    _id: "1044",
    table: {
      id: "table_08",
      number: "08",
      floor: "Indoor Area",
      status: "Occupied",
    },
    customer: {
      name: "Table Guest",
    },
    items: [
      {
        productId: "p2",
        name: "Paneer Tikka",
        quantity: 2,
        price: 24.0,
        addons: ["Extra Spicy"],
        image: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=150&q=80",
      },
    ],
    subtotal: 48.0,
    tax: 3.84,
    serviceCharge: 4.8,
    total: 56.64,
    status: "READY",
    waiter: {
      id: "w3",
      name: "David P.",
      avatar: "DP",
      ordersToday: 18,
    },
    timeline: [
      {
        status: "PLACED",
        timestamp: "15:10",
        performedBy: "Customer",
      },
      {
        status: "CONFIRMED",
        timestamp: "15:12",
        performedBy: "David P.",
      },
      {
        status: "PREPARING",
        timestamp: "15:14",
        performedBy: "Kitchen",
      },
      {
        status: "READY",
        timestamp: "15:32",
        performedBy: "Kitchen",
        note: "Awaiting pickup by David P.",
      },
    ],
    createdAt: "2026-08-20T15:10:00.000Z",
    updatedAt: "2026-08-20T15:32:00.000Z",
  },
  {
    _id: "1045",
    table: {
      id: "table_12",
      number: "12",
      floor: "Main Floor",
      status: "Occupied",
    },
    customer: {
      name: "Table Guest",
    },
    items: [
      {
        productId: "p11",
        name: "Garlic Butter Naan",
        quantity: 4,
        price: 4.0,
        addons: [],
      },
      {
        productId: "p12",
        name: "Butter Chicken",
        quantity: 1,
        price: 28.0,
        addons: [],
      },
    ],
    subtotal: 44.0,
    tax: 3.52,
    serviceCharge: 4.4,
    total: 51.92,
    status: "PREPARING",
    waiter: {
      id: "w1",
      name: "Arun K.",
      avatar: "AK",
      ordersToday: 14,
    },
    timeline: [
      {
        status: "PLACED",
        timestamp: "15:15",
        performedBy: "Customer",
      },
      {
        status: "CONFIRMED",
        timestamp: "15:16",
        performedBy: "Arun K.",
      },
      {
        status: "PREPARING",
        timestamp: "15:18",
        performedBy: "Kitchen",
      },
    ],
    createdAt: "2026-08-20T15:15:00.000Z",
    updatedAt: "2026-08-20T15:18:00.000Z",
  },
];
